apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacmangit
  namespace: pacmangit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacmangit
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacmangit
  namespace: pacmangit
subjects:
- kind: ServiceAccount
  name: pacmangitpwd
  
  namespace: pacmangit
roleRef:
  kind: ClusterRole
  name: pacmangit
  apiGroup: rbac.authorization.k8s.io